# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\video_source.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(589, 300)
        self.video_sources = QtWidgets.QComboBox(Dialog)
        self.video_sources.setGeometry(QtCore.QRect(70, 70, 401, 31))
        self.video_sources.setCurrentText("")
        self.video_sources.setObjectName("video_sources")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(70, 160, 351, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.file_btn = QtWidgets.QPushButton(Dialog)
        self.file_btn.setGeometry(QtCore.QRect(440, 160, 41, 31))
        self.file_btn.setObjectName("file_btn")
        self.start_btn = QtWidgets.QPushButton(Dialog)
        self.start_btn.setGeometry(QtCore.QRect(460, 240, 111, 41))
        self.start_btn.setObjectName("start_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 30, 251, 41))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setEnabled(True)
        self.checkBox.setGeometry(QtCore.QRect(70, 130, 161, 31))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Choose  video source"))
        self.file_btn.setText(_translate("Dialog", "..."))
        self.start_btn.setText(_translate("Dialog", "start"))
        self.label.setText(_translate("Dialog", "Choose video source"))
        self.checkBox.setText(_translate("Dialog", "Or choose video file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
